tf_gnss_csv_node:
  ros__parameters:

    # CARLA 경로 (f9r_to_csv.py로 생성)
    # bag 기록: ros2 bag record -o gnss_data/ros2bag/<name> /carla/car/f9r/fix
    # CSV 생성: f9r_to_csv.py 실행 → gnss_data/csv/<name>.csv

    # # route_1
    csv_file_path: "/home/hannibal/carla/mppi/src/gnss_to_utm/gnss_data/csv/route_1.csv"

    # # route_2
    # csv_file_path: "/home/hannibal/carla/mppi/src/gnss_to_utm/gnss_data/csv/route_2.csv"